### ISSUE TITLE
the En-big-en-ing

### ISSUE THREAD

**Issue by ghost** [free5ty1e/primestationone-control-android#35]
Hello. Would it be possible to either add the ability to rotate screens, or at least zoom in on the spashscreen when it is displayed? I think it might be helpful for people with small screens and or bad eyes -- like me :-)

**Comment by free5ty1e** [comment]
Certainly; was going to be one of the next things I tackled anyway xD

**Comment by free5ty1e** [comment]
v0.2.1 in the play store was just released, now displays in landscape mode :D
